### ISSUE TITLE
User Experience - Suggestions for Improvement

### ISSUE THREAD

**Issue by UnitedWithCode** [soupslurpr/Transcribro#49]
This voice keyboard app for Android phones is fantastic! I really enjoy using it. The error rate is quite low. There are just a couple of things I think could be improved. 

First, would it be possible to turn off the sound notification that plays when you start and stop recording? 

Second, when you start recording, a message letting the user know it's recording would be helpful. Similarly, when you stop recording, a loading or processing sign would be great. Right now, I press stop and don't know how long the processing will take. From a user interface standpoint, these small changes would make a big difference.

**Comment by soupslurpr** [comment]
Heyy thanks for the feedback!

1. It only plays when the system ringer is set to sound, similar to other voice inputs I've seen such as Google's.
2. I think the fact that its recording is adequately shown with it being toggled + the system showing the microphone access indicator at the top right. I initially tried to implement an infinite loading circle as a sign its processing but failed to because it added padding that messed with the rest of the UI. I may try to do that again, but since we don't know the actual progress of the transcription (due to how the model works), it has to remain an infinite loading circle rather than one that advances with progress. Perhaps there could be an estimated time remaining based on the length of the audio and average of previous runs but its still dependent on how fast you speak and possibly other factors too.

**Comment by soupslurpr** [comment]
I agree but as I said the infinite loading loop may not work due to it adding padding. A progress bar at the top of the recognition toggle should work.

**Comment by soupslurpr** [comment]
BTW I created #51 and #53 to address those points.
