### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by shuvashish76** [soupslurpr/Transcribro#9]
Hello, would you consider publishing the app on F-Droid please?

**Comment by soupslurpr** [comment]
Hi, sorry but F-Droid doesn't meet my requirements. I recommend getting Transcribro from Accrescent though so you can get higher security than GitHub releases and (optional, but reccomended. Can turn off and just get notifications when an update is available.) automatic updates.

**Comment by soupslurpr** [comment]
I think this article explains some of the issues with F-Droid well: https://privsec.dev/posts/android/f-droid-security-issues/

Accrescent is more secure and has faster updates.

**Comment by hoh** [comment]
What guarantee would I have that Transcribro remains open-source and build from the published sources if I install it from Accrescent ?

**Comment by soupslurpr** [comment]
@hoh while you wouldn't have a guarantee that it remains open-source (Accrescent doesn't have reproducible builds like F-Droid does), would you review every single line of Transcribro's code and the newly added code before installing the update for the new version? If not, then you are trusting me. I can assure you Transcribro will remain open-source.

**Comment by soupslurpr** [comment]
> It's still possible to have own repository (e.g.: https://f-droid.org/en/docs/Setup_an_F-Droid_App_Repo/) that gives you complete control, security (you build and sign the code) and fast update (it's updated when you publish the artifact).

I don't wish to host my own repository, and Accrescent would still be preferred due to its root of trust to the OS signing key on GrapheneOS. I acknowledge that doesn't matter if you aren't using GrapheneOS (which I highly recommend using) but Accrescent still has the benefit of not accepting app updates that add sensitive permissions without review with rationale. (https://accrescent.app/docs/guide/appendix/requirements.html#sensitive-permissions)

**Comment by shuvashish76** [comment]
> if you aren't using GrapheneOS (which I highly recommend using)

"Recommended" but the reality is it's not an option for many people.

> would you oppose including Transcribro in f-droid (either directly in their repo or via IzzyOnDroid)?

Not possible as they allow upto 30MB (see their [inclusion policy](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Inclusion%20Policy))

> I think this article explains some of the issues with F-Droid well: https://privsec.dev/posts/android/f-droid-security-issues/

Some issues really doesn't make any sense to me, some I don't agree. No point in discussing them here.
I agree F-Droid has it's issues and they're trying to improve certain things. So far F-Droid is the largest FOSS appstore for users, we don't have any other alternative.
Inclusion shouldn't matter with _personal preference_. You might not agree with F-Droid's philosophy but still possible to publish on F-Droid for users. e.g. [Obtainium devs motivation was to move away from F-Droid](https://github.com/ImranR98/Obtainium/issues/30#issuecomment-1257019717), still they manage to publish F-Droid flavor on FD.

We respect your decision regardless you publish on FD or not, thank you for Transcribro as a foss project :D

> Accrescent is more secure and has faster updates.

One major reason for not using it is lack of apps. Their devs recommend reaching out to app devs for inclusion as it's not yet stable enough for developers.

**Comment by soupslurpr** [comment]
> Some issues really doesn't make any sense to me, some I don't agree. No point in discussing them here. I agree F-Droid has it's issues and they're trying to improve certain things. So far F-Droid is the largest FOSS appstore for users, we don't have any other alternative. Inclusion shouldn't matter with _personal preference_. You might not agree with F-Droid's philosophy but still possible to publish on F-Droid for users. e.g. [Obtainium devs motivation was to move away from F-Droid](https://github.com/ImranR98/Obtainium/issues/30#issuecomment-1257019717), still they manage to publish F-Droid flavor on FD.
> 
> We respect your decision regardless you publish on FD or not, thank you for Transcribro as a foss project :D

It's mostly just the update delays I think can be dangerous. I certainly don't want people getting delayed updates, especially when they could be security updates :)

> One major reason for not using it is lack of apps. Their devs don't recommend reaching out to app devs for inclusion as it's not yet stable enough for developers.

While that is true, it will reach open beta someday. I foresee it getting many more apps.

> As the appstore grows human review will be difficult to manage. F-Droid improved some parts https://gitlab.com/fdroid/issuebot/-/merge_requests/82 (only issuebot i.e. new apps) , https://gitlab.com/fdroid/fdroidserver/-/merge_requests/1463 far from perfect though.

Remember that human review is only for the initial publication of apps and apps which add new sensitive permissions through updates. Because of that I don't think Accrescent has too much of a bigger human review burden than other stores. Its also a nice feature in that apps won't be able to use/request sensitive permissions without reason.
One example is a text editor app requesting access to all files when it only needs specific files and thus should use the Android Storage Access Framework (SAF) to access those specific files with the user's consent rather than all files.
